# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='gov_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
