# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=' ', max_length=999),
            preserve_default=False,
        ),
    ]
