# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170725_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='gov_id',
            field=models.CharField(max_length=255),
        ),
    ]
