# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
